#version 460 core

#define CELL_INDEX_BUFFER 4
#define PARTICLE_INDEX_BUFFER 5
#define GLOBAL_OFFSET_BUFFER 7
#define BLOCK_SUM_BUFFER 8

#define PARTICLE_COUNT 256
#define THREADS_PER_GROUP 256

#define NUM_BANKS 32
#define LOG_NUM_BANKS 5

/*
 macro to shift indices preventing bank conflicts
 as described by Mark Harris in "GPU Gems 3: Chapter 39"
 subsection 39.2.3 'Avoiding Bank Conflicts'
*/ 
#define CONFLICT_FREE_OFFSET(n) ((n) >> LOG_NUM_BANKS) 
#define CONFLICT_FREE_INDEX(n) (CONFLICT_FREE_OFFSET(n) + n)

layout(local_size_x = THREADS_PER_GROUP, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = CELL_INDEX_BUFFER) buffer CellIndexBuff { uint cellIndexBuff[]; };
layout(std430, binding = PARTICLE_INDEX_BUFFER) buffer ParticleIndexBuff { uint particleIndexBuff[]; };
layout(std430, binding = GLOBAL_OFFSET_BUFFER) buffer GlobalOffsetBuff { uint globalOffsetBuff[]; };
layout(std430, binding = BLOCK_SUM_BUFFER) buffer BlockSumBuff { uint blockSumBuff[]; };

// 32 uints for padding to avoid bank conflict
shared uint s_counts[PARTICLE_COUNT * 4 + 32];
shared uint local_offsets[4];

shared uint s_keys[PARTICLE_COUNT];
shared uint s_vals[PARTICLE_COUNT];

shared uint s_keys_shuffled[PARTICLE_COUNT];
shared uint s_vals_shuffled[PARTICLE_COUNT];

uniform int totalParticleCount;
uniform int workGroupCount;
uniform int passCount;
uniform int shift_key;

void
main() {
    uint globalThreadIndex = gl_GlobalInvocationID.x;
    uint workGroupIndex = gl_WorkGroupID.x;
    uint localThreadIndex = gl_LocalInvocationIndex;

    uint totalParticleCountU = uint(totalParticleCount);
    uint workGroupCountU = uint(workGroupCount);
    uint passCountU = uint(passCount);
    uint shiftKeyU = uint(shift_key);

    bool validThread = globalThreadIndex < totalParticleCountU;

    uint digit_offset_zero  = 0 * PARTICLE_COUNT;   
    uint digit_offset_one   = 1 * PARTICLE_COUNT;   
    uint digit_offset_two   = 2 * PARTICLE_COUNT;   
    uint digit_offset_three = 3 * PARTICLE_COUNT;   

    // reset shared memory values
    uint reset_index_zero  = 0 * PARTICLE_COUNT + localThreadIndex;
    uint reset_index_one   = 1 * PARTICLE_COUNT + localThreadIndex;
    uint reset_index_two   = 2 * PARTICLE_COUNT + localThreadIndex;
    uint reset_index_three = 3 * PARTICLE_COUNT + localThreadIndex;

    uint conflict_free_reset_index_zero  = CONFLICT_FREE_INDEX(reset_index_zero);
    uint conflict_free_reset_index_one   = CONFLICT_FREE_INDEX(reset_index_one);
    uint conflict_free_reset_index_two   = CONFLICT_FREE_INDEX(reset_index_two);
    uint conflict_free_reset_index_three = CONFLICT_FREE_INDEX(reset_index_three);

    s_counts[conflict_free_reset_index_zero]  = 0;
    s_counts[conflict_free_reset_index_one]   = 0;
    s_counts[conflict_free_reset_index_two]   = 0;
    s_counts[conflict_free_reset_index_three] = 0;

    uint key = 0xFFFFFFFFu;
    uint val = 0xFFFFFFFFu;

    if (validThread) {
        key = cellIndexBuff[globalThreadIndex];
        val = particleIndexBuff[globalThreadIndex];
    }
    barrier();

    // cache original values in local storage for final shuffle
    s_keys[localThreadIndex] = key;
    s_vals[localThreadIndex] = val;

    uint d = 0u;
    if (validThread) {
        d = (key >> shiftKeyU) & 3u;
        uint mask_index = d * PARTICLE_COUNT + localThreadIndex;
        s_counts[CONFLICT_FREE_INDEX(mask_index)] = 1;
    }
    barrier();

    /*
     *************************************
     *********** SWEEP UP PHASE***********
     *************************************
    */

    // pass count for 256 elements is log2(256) i.e. 8
    for (int pass = 0; pass < passCount; ++pass) {
        
        // array index stride per pass
        uint stride = 1u << pass; 
        
        // Maximum threads that can process the buffer for current pass
        uint maxThreadsForCurrentPass = THREADS_PER_GROUP >> pass;
        
        if (localThreadIndex < maxThreadsForCurrentPass) {

            uint s_index = (localThreadIndex + 1) * (2 * stride) - 1;

            uint right_index_zero  = digit_offset_zero  + s_index;
            uint right_index_one   = digit_offset_one   + s_index;
            uint right_index_two   = digit_offset_two   + s_index;
            uint right_index_three = digit_offset_three + s_index;

            uint left_index_zero  = right_index_zero - stride;
            uint left_index_one   = right_index_one - stride;
            uint left_index_two   = right_index_two - stride;
            uint left_index_three = right_index_three - stride;

            uint right_child_zero  = CONFLICT_FREE_INDEX(right_index_zero);  
            uint left_child_zero = CONFLICT_FREE_INDEX(left_index_zero);

            uint right_child_one  = CONFLICT_FREE_INDEX(right_index_one);  
            uint left_child_one = CONFLICT_FREE_INDEX(left_index_one);

            uint right_child_two  = CONFLICT_FREE_INDEX(right_index_two);  
            uint left_child_two = CONFLICT_FREE_INDEX(left_index_two);

            uint right_child_three  = CONFLICT_FREE_INDEX(right_index_three);  
            uint left_child_three = CONFLICT_FREE_INDEX(left_index_three);

            s_counts[right_child_zero]  += s_counts[left_child_zero];
            s_counts[right_child_one]   += s_counts[left_child_one];
            s_counts[right_child_two]   += s_counts[left_child_two];
            s_counts[right_child_three] += s_counts[left_child_three];
        }
        barrier();
    } 

    // reset root values
    if (localThreadIndex < 4) {

        uint digit = localThreadIndex;

        uint root_index  = digit * PARTICLE_COUNT + PARTICLE_COUNT - 1u; 
        uint conflict_free_root_index  = CONFLICT_FREE_INDEX(root_index);

        local_offsets[digit] = s_counts[conflict_free_root_index];
        uint globalOffsetAndBlockSumBufferIndex = (digit * workGroupCountU) + workGroupIndex;
        globalOffsetBuff[globalOffsetAndBlockSumBufferIndex] = s_counts[conflict_free_root_index]; 
        blockSumBuff[globalOffsetAndBlockSumBufferIndex] = s_counts[conflict_free_root_index];

        s_counts[conflict_free_root_index] = 0u;
    }
    barrier();

    if (localThreadIndex == 0) {
        local_offsets[3] = local_offsets[2] + local_offsets[1] + local_offsets[0];
        local_offsets[2] = local_offsets[1] + local_offsets[0];
        local_offsets[1] = local_offsets[0];
        local_offsets[0] = 0;
    }
    barrier();

    /*
     ***************************************
     *********** DOWN SWEEP PHASE***********
     ***************************************
    */

    for(uint pass = 0u; pass < passCountU; ++pass) {
        uint stride = 1u << (passCountU - pass - 1u);
        uint offset = 1u << pass;

        uint maxThreadsForCurrentPass = THREADS_PER_GROUP >> (passCountU - pass - 1u);
        
        if (localThreadIndex < maxThreadsForCurrentPass) {

            uint s_index = (offset - localThreadIndex) * (2 * stride) - 1;

            uint right_index_zero  = digit_offset_zero  + s_index;
            uint right_index_one   = digit_offset_one   + s_index;
            uint right_index_two   = digit_offset_two   + s_index;
            uint right_index_three = digit_offset_three + s_index;

            uint left_index_zero  = right_index_zero - stride;
            uint left_index_one   = right_index_one - stride;
            uint left_index_two   = right_index_two - stride;
            uint left_index_three = right_index_three - stride;

            uint conflict_free_right_index_zero 
                    = CONFLICT_FREE_INDEX(right_index_zero);  
            uint conflict_free_left_index_zero 
                    = CONFLICT_FREE_INDEX(left_index_zero);

            uint conflict_free_right_index_one 
                    = CONFLICT_FREE_INDEX(right_index_one);  
            uint conflict_free_left_index_one 
                    = CONFLICT_FREE_INDEX(left_index_one);

            uint conflict_free_right_index_two 
                    = CONFLICT_FREE_INDEX(right_index_two);  
            uint conflict_free_left_index_two 
                    = CONFLICT_FREE_INDEX(left_index_two);

            uint conflict_free_right_index_three 
                    = CONFLICT_FREE_INDEX(right_index_three);  
            uint conflict_free_left_index_three 
                    = CONFLICT_FREE_INDEX(left_index_three);

            // save left child
            uint left_child_zero = s_counts[conflict_free_left_index_zero];
            s_counts[conflict_free_left_index_zero] = s_counts[conflict_free_right_index_zero];
            s_counts[conflict_free_right_index_zero] += left_child_zero; 

            uint left_child_one = s_counts[conflict_free_left_index_one];
            s_counts[conflict_free_left_index_one] = s_counts[conflict_free_right_index_one];
            s_counts[conflict_free_right_index_one] += left_child_one; 

            uint left_child_two = s_counts[conflict_free_left_index_two];
            s_counts[conflict_free_left_index_two] = s_counts[conflict_free_right_index_two];
            s_counts[conflict_free_right_index_two] += left_child_two; 

            uint left_child_three = s_counts[conflict_free_left_index_three];
            s_counts[conflict_free_left_index_three] = s_counts[conflict_free_right_index_three];
            s_counts[conflict_free_right_index_three] += left_child_three; 
        }
        barrier();
    }

    // in-block shuffle

    // First element of the thread
    if (globalThreadIndex < totalParticleCountU) {
        uint offset = local_offsets[d];
        uint prefixSumIndex = d * PARTICLE_COUNT + localThreadIndex;
        uint conflictFreePrefixSumIndex = CONFLICT_FREE_INDEX(prefixSumIndex);
        uint prefixSum = s_counts[conflictFreePrefixSumIndex];
        uint final_dest = offset + prefixSum;

        s_keys_shuffled[final_dest] = key;
        s_vals_shuffled[final_dest] = val;
    }
    barrier();

    // write back sorted values
    if (globalThreadIndex < totalParticleCountU) {
        cellIndexBuff[globalThreadIndex] = s_keys_shuffled[localThreadIndex];
        particleIndexBuff[globalThreadIndex] = s_vals_shuffled[localThreadIndex];
    }
}